export enum ColorEnum {
	DEFAULT = 'default',
	DEFAULT_DARK = 'defaultDark',
	EMPHASIZE = 'emphasize',
	NORMAL = 'normal',
	SUBTLE_1 = 'subtle-1',
	SUBTLE_2 = 'subtle-2',
	BG_INPUT = 'bg-input',
	BG_2 = 'bg-2',
	PRIMARY_1 = 'primary-1',
	PRIMARY = 'primary',
	PRIMARY_2 = 'primary-2',
	PRIMARY_3 = 'primary-3',
	PRIMARY_BG = 'primary-bg',
	SECONDARY = 'secondary',
	MID = 'midd',
	WARNING = 'warning',
	PRIMARY_SUBTLE = 'primary-subtle',
	LINE = 'line',

	NEGATAVE = 'negative',
	POSITIVE = 'positive',
	LIGHT = 'light',
	DARK = 'dark',
	INFO = 'info',

	GREY100 = 'grey100',
	GREY200 = 'grey200',
	GREY300 = 'grey300',
	GREY400 = 'grey400',
	GREY500 = 'grey500',
	GREY600 = 'grey600',
	GREY700 = 'grey700',
	GREY800 = 'grey800',
	GREY900 = 'grey900',

	DISABLED = 'disabled',
	CANCEL = 'cancel',
}
