/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthCode: typeof import('./components/AuthCode.vue')['default']
    LoginView: typeof import('./components/Login/LoginView.vue')['default']
    NavbarDrawer: typeof import('./components/drawer/NavbarDrawer.vue')['default']
    RegisterView: typeof import('./components/Login/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperOne: typeof import('./components/Swiper/SwiperOne.vue')['default']
    SwiperThree: typeof import('./components/Swiper/SwiperThree.vue')['default']
    SwiperTwo: typeof import('./components/Swiper/SwiperTwo.vue')['default']
  }
}
